---
- name: Dependency | Setup virtualenv path
  set_fact:
    ansible_python_interpreter_current: "{{ ansible_python.executable }}"

- name: Dependency | Install python libraries
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ cloud_cdn_venv_tmp }}"
    virtualenv_site_packages: yes
  with_items: "{{ cloud_cdn_dependencies }}"

- name: Dependency | Set tasks to use custom Virtualenv used by custom libraries
  set_fact:
    ansible_python_interpreter: "{{ cloud_cdn_venv_tmp }}/bin/python"
