---
- include: dependency.yml

- name: AZION - Getting CDN config by ID
  azion_cdn_facts:
    id: "{{ azion_cdn_id }}"
  when: azion_cdn_id is defined

- name: AZION - Getting CDN config by NAME
  azion_cdn_facts:
    name: "{{ azion_cdn_name }}"
  when: azion_cdn_name is defined


# - set_fact:
#     azion_cdn_name: busca-aws-carrodemola
#
# - name: AZION - Getting CDN config by NAME
#   azion_cdn_facts:
#     name: "{{ azion_cdn_name }}"
#   when: azion_cdn_name is defined
