---
- include: dependency.yml

- name: AZION - Creating CDN using payload
  when: azion_cdn_name is defined
  azion_cdn_create:
    name: "{{ azion_cdn_name }}"
    state: present
    payload: "{{ cdn_payload }}"

- name: AZION - Creating CDN using sample
  when: azion_cdn_name is defined
  azion_cdn_create:
    name: "{{ azion_cdn_name }}-sample"
    state: present

- name: AZION - Getting CDN config by ID
  azion_cdn_facts:
    id: "{{ azion_cdn_id }}"
  when: azion_cdn_id is defined

- name: AZION - Getting CDN config by NAME
  azion_cdn_facts:
    name: "{{ azion_cdn_name }}"
  when: azion_cdn_name is defined

- name: AZION - Getting CDN config by NAME
  azion_cdn_facts:
    name: "{{ azion_cdn_name }}-sample"
  when: azion_cdn_name is defined
