---
- include: dependency.yml
  tags: always

- block:
    - name: AZION CDN config
      include: azion_cdn.yml
      when: item_cdn.provider == 'azion'
      with_items: "{{ cdn_distributions }}"
      loop_control:
        loop_var: item_cdn

  rescue:
    - meta: flush_handlers

  always:
    - name: Main | Return to original Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ ansible_python_interpreter_current }}"
